version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - revive
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused
  settings:
    revive:
      severity: warning
