version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - revive
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused

linters-settings:
  revive:
    severity: warning
