name: ci-checks

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Go format
        run: |
          test -z "$(gofmt -s -l .)"

      - name: Go vet
        run: go vet ./...

      - name: Go test
        run: go test ./...

      - name: Go build
        run: go build ./...
